
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import UmbraEscrowContractArtifactJson from '../target/umbra_escrow-UmbraEscrow.json' with { type: 'json' };
export const UmbraEscrowContractArtifact = loadContractArtifact(UmbraEscrowContractArtifactJson as NoirCompiledContract);


      export type OrderFilled = {
        escrow_id: FieldLike
      }
    

      export type OrderCreated = {
        escrow_id: FieldLike
sell_token: AztecAddressLike
buy_token: AztecAddressLike
      }
    

      export type OrderCancelled = {
        escrow_id: FieldLike
      }
    

/**
 * Type-safe interface for contract UmbraEscrow;
 */
export class UmbraEscrowContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, UmbraEscrowContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, UmbraEscrowContract.artifact, wallet) as Promise<UmbraEscrowContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, fee_recipient: AztecAddressLike, fee_bps: FieldLike) {
    return new DeployMethod<UmbraEscrowContract>(PublicKeys.default(), wallet, UmbraEscrowContractArtifact, UmbraEscrowContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, fee_recipient: AztecAddressLike, fee_bps: FieldLike) {
    return new DeployMethod<UmbraEscrowContract>(publicKeys, wallet, UmbraEscrowContractArtifact, UmbraEscrowContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof UmbraEscrowContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<UmbraEscrowContract['methods'][M]>
  ) {
    return new DeployMethod<UmbraEscrowContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      UmbraEscrowContractArtifact,
      UmbraEscrowContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return UmbraEscrowContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(UmbraEscrowContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'fee_recipient' | 'fee_bps' | 'paused' | 'order_count' | 'total_volume' | 'order_exists' | 'order_seller' | 'order_sell_token' | 'order_sell_amount' | 'order_buy_token' | 'order_buy_amount' | 'order_deadline' | 'order_filled'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
fee_recipient: {
      slot: new Fr(3n),
    },
fee_bps: {
      slot: new Fr(4n),
    },
paused: {
      slot: new Fr(5n),
    },
order_count: {
      slot: new Fr(6n),
    },
total_volume: {
      slot: new Fr(7n),
    },
order_exists: {
      slot: new Fr(8n),
    },
order_seller: {
      slot: new Fr(9n),
    },
order_sell_token: {
      slot: new Fr(10n),
    },
order_sell_amount: {
      slot: new Fr(11n),
    },
order_buy_token: {
      slot: new Fr(12n),
    },
order_buy_amount: {
      slot: new Fr(13n),
    },
order_deadline: {
      slot: new Fr(14n),
    },
order_filled: {
      slot: new Fr(15n),
    }
      } as ContractStorageLayout<'admin' | 'fee_recipient' | 'fee_bps' | 'paused' | 'order_count' | 'total_volume' | 'order_exists' | 'order_seller' | 'order_sell_token' | 'order_sell_amount' | 'order_buy_token' | 'order_buy_amount' | 'order_deadline' | 'order_filled'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cancel_order(escrow_id: field, sell_token: struct, sell_amount: field, nonce: field) */
    cancel_order: ((escrow_id: FieldLike, sell_token: AztecAddressLike, sell_amount: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, fee_recipient: struct, fee_bps: field) */
    constructor: ((admin: AztecAddressLike, fee_recipient: AztecAddressLike, fee_bps: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_order(sell_token: struct, sell_amount: field, buy_token: struct, buy_amount: field, deadline: field, nonce: field) */
    create_order: ((sell_token: AztecAddressLike, sell_amount: FieldLike, buy_token: AztecAddressLike, buy_amount: FieldLike, deadline: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** fill_order(escrow_id: field, seller: struct, sell_token: struct, sell_amount: field, buy_token: struct, buy_amount: field, fee_recipient: struct, fee_bps: field, nonce: field) */
    fill_order: ((escrow_id: FieldLike, seller: AztecAddressLike, sell_token: AztecAddressLike, sell_amount: FieldLike, buy_token: AztecAddressLike, buy_amount: FieldLike, fee_recipient: AztecAddressLike, fee_bps: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_fee_bps() */
    get_fee_bps: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_fee_recipient() */
    get_fee_recipient: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_buy_amount(escrow_id: field) */
    get_order_buy_amount: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_count() */
    get_order_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_sell_amount(escrow_id: field) */
    get_order_sell_amount: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_seller(escrow_id: field) */
    get_order_seller: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_volume() */
    get_total_volume: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_order_filled(escrow_id: field) */
    is_order_filled: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_paused() */
    is_paused: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** order_exists(escrow_id: field) */
    order_exists: ((escrow_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause() */
    pause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_fee(new_fee_bps: field) */
    set_fee: ((new_fee_bps: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_fee_recipient(new_recipient: struct) */
    set_fee_recipient: ((new_recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause() */
    unpause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { OrderFilled: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, OrderCreated: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, OrderCancelled: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      OrderFilled: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "escrow_id",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "UmbraEscrow::OrderFilled"
},
        eventSelector: EventSelector.fromString("0x93140278"),
        fieldNames: ["escrow_id"],
      },
OrderCreated: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "escrow_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "sell_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "buy_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "UmbraEscrow::OrderCreated"
},
        eventSelector: EventSelector.fromString("0xe77e91a0"),
        fieldNames: ["escrow_id","sell_token","buy_token"],
      },
OrderCancelled: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "escrow_id",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "UmbraEscrow::OrderCancelled"
},
        eventSelector: EventSelector.fromString("0x2e840de7"),
        fieldNames: ["escrow_id"],
      }
    };
  }
  
}
