
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import UmbraPoolContractArtifactJson from '../target/umbra_pool-UmbraPool.json' with { type: 'json' };
export const UmbraPoolContractArtifact = loadContractArtifact(UmbraPoolContractArtifactJson as NoirCompiledContract);


      export type PairAdded = {
        base_token: AztecAddressLike
quote_token: AztecAddressLike
      }
    

      export type OrderSubmitted = {
        order_id: FieldLike
base_token: AztecAddressLike
quote_token: AztecAddressLike
side: FieldLike
      }
    

      export type OrderMatched = {
        buy_order_id: FieldLike
sell_order_id: FieldLike
amount: FieldLike
price: FieldLike
      }
    

      export type OrderCancelled = {
        order_id: FieldLike
      }
    

/**
 * Type-safe interface for contract UmbraPool;
 */
export class UmbraPoolContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, UmbraPoolContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, UmbraPoolContract.artifact, wallet) as Promise<UmbraPoolContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, oracle: AztecAddressLike, fee_recipient: AztecAddressLike, taker_fee_bps: FieldLike, maker_fee_bps: FieldLike) {
    return new DeployMethod<UmbraPoolContract>(PublicKeys.default(), wallet, UmbraPoolContractArtifact, UmbraPoolContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, oracle: AztecAddressLike, fee_recipient: AztecAddressLike, taker_fee_bps: FieldLike, maker_fee_bps: FieldLike) {
    return new DeployMethod<UmbraPoolContract>(publicKeys, wallet, UmbraPoolContractArtifact, UmbraPoolContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof UmbraPoolContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<UmbraPoolContract['methods'][M]>
  ) {
    return new DeployMethod<UmbraPoolContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      UmbraPoolContractArtifact,
      UmbraPoolContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return UmbraPoolContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(UmbraPoolContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'oracle' | 'fee_recipient' | 'taker_fee_bps' | 'maker_fee_bps' | 'total_volume' | 'total_matches' | 'order_count' | 'paused' | 'order_exists' | 'order_owner' | 'order_base_token' | 'order_quote_token' | 'order_side' | 'order_amount' | 'order_filled_amount' | 'order_limit_price' | 'order_expires_at' | 'supported_pairs'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
oracle: {
      slot: new Fr(3n),
    },
fee_recipient: {
      slot: new Fr(4n),
    },
taker_fee_bps: {
      slot: new Fr(5n),
    },
maker_fee_bps: {
      slot: new Fr(6n),
    },
total_volume: {
      slot: new Fr(7n),
    },
total_matches: {
      slot: new Fr(8n),
    },
order_count: {
      slot: new Fr(9n),
    },
paused: {
      slot: new Fr(10n),
    },
order_exists: {
      slot: new Fr(11n),
    },
order_owner: {
      slot: new Fr(12n),
    },
order_base_token: {
      slot: new Fr(13n),
    },
order_quote_token: {
      slot: new Fr(14n),
    },
order_side: {
      slot: new Fr(15n),
    },
order_amount: {
      slot: new Fr(16n),
    },
order_filled_amount: {
      slot: new Fr(17n),
    },
order_limit_price: {
      slot: new Fr(18n),
    },
order_expires_at: {
      slot: new Fr(19n),
    },
supported_pairs: {
      slot: new Fr(20n),
    }
      } as ContractStorageLayout<'admin' | 'oracle' | 'fee_recipient' | 'taker_fee_bps' | 'maker_fee_bps' | 'total_volume' | 'total_matches' | 'order_count' | 'paused' | 'order_exists' | 'order_owner' | 'order_base_token' | 'order_quote_token' | 'order_side' | 'order_amount' | 'order_filled_amount' | 'order_limit_price' | 'order_expires_at' | 'supported_pairs'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_pair(base_token: struct, quote_token: struct) */
    add_pair: ((base_token: AztecAddressLike, quote_token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** cancel_order(order_id: field, base_token: struct, quote_token: struct, side: field, amount: field, filled_amount: field, limit_price: field, nonce: field) */
    cancel_order: ((order_id: FieldLike, base_token: AztecAddressLike, quote_token: AztecAddressLike, side: FieldLike, amount: FieldLike, filled_amount: FieldLike, limit_price: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, oracle: struct, fee_recipient: struct, taker_fee_bps: field, maker_fee_bps: field) */
    constructor: ((admin: AztecAddressLike, oracle: AztecAddressLike, fee_recipient: AztecAddressLike, taker_fee_bps: FieldLike, maker_fee_bps: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_fee_recipient() */
    get_fee_recipient: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_maker_fee() */
    get_maker_fee: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_oracle() */
    get_oracle: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_amount(order_id: field) */
    get_order_amount: ((order_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_count() */
    get_order_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_filled_amount(order_id: field) */
    get_order_filled_amount: ((order_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_limit_price(order_id: field) */
    get_order_limit_price: ((order_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_order_owner(order_id: field) */
    get_order_owner: ((order_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_taker_fee() */
    get_taker_fee: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_matches() */
    get_total_matches: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_total_volume() */
    get_total_volume: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_pair_supported(base_token: struct, quote_token: struct) */
    is_pair_supported: ((base_token: AztecAddressLike, quote_token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_paused() */
    is_paused: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** match_orders(buy_order_id: field, sell_order_id: field, match_amount: field, oracle_price: field, buy_owner: struct, buy_limit_price: field, sell_owner: struct, sell_base_token: struct, sell_quote_token: struct, sell_limit_price: field, buy_nonce: field, sell_nonce: field) */
    match_orders: ((buy_order_id: FieldLike, sell_order_id: FieldLike, match_amount: FieldLike, oracle_price: FieldLike, buy_owner: AztecAddressLike, buy_limit_price: FieldLike, sell_owner: AztecAddressLike, sell_base_token: AztecAddressLike, sell_quote_token: AztecAddressLike, sell_limit_price: FieldLike, buy_nonce: FieldLike, sell_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** order_exists(order_id: field) */
    order_exists: ((order_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause() */
    pause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_pair(base_token: struct, quote_token: struct) */
    remove_pair: ((base_token: AztecAddressLike, quote_token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_fee_recipient(new_recipient: struct) */
    set_fee_recipient: ((new_recipient: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_maker_fee(new_fee_bps: field) */
    set_maker_fee: ((new_fee_bps: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_oracle(new_oracle: struct) */
    set_oracle: ((new_oracle: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_taker_fee(new_fee_bps: field) */
    set_taker_fee: ((new_fee_bps: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** submit_limit_order(base_token: struct, quote_token: struct, side: field, amount: field, limit_price: field, expires_in_blocks: field, nonce: field) */
    submit_limit_order: ((base_token: AztecAddressLike, quote_token: AztecAddressLike, side: FieldLike, amount: FieldLike, limit_price: FieldLike, expires_in_blocks: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** submit_market_order(base_token: struct, quote_token: struct, side: field, amount: field, expires_in_blocks: field, nonce: field) */
    submit_market_order: ((base_token: AztecAddressLike, quote_token: AztecAddressLike, side: FieldLike, amount: FieldLike, expires_in_blocks: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause() */
    unpause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { PairAdded: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, OrderSubmitted: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, OrderMatched: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, OrderCancelled: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      PairAdded: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "base_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "quote_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "UmbraPool::PairAdded"
},
        eventSelector: EventSelector.fromString("0xbd82207b"),
        fieldNames: ["base_token","quote_token"],
      },
OrderSubmitted: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "order_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "base_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "quote_token",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "side",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "UmbraPool::OrderSubmitted"
},
        eventSelector: EventSelector.fromString("0x65653bc8"),
        fieldNames: ["order_id","base_token","quote_token","side"],
      },
OrderMatched: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "buy_order_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "sell_order_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "price",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "UmbraPool::OrderMatched"
},
        eventSelector: EventSelector.fromString("0xf7c41e0b"),
        fieldNames: ["buy_order_id","sell_order_id","amount","price"],
      },
OrderCancelled: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "order_id",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "UmbraPool::OrderCancelled"
},
        eventSelector: EventSelector.fromString("0x2e840de7"),
        fieldNames: ["order_id"],
      }
    };
  }
  
}
